# Generated by Django 2.2.28 on 2023-06-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_zaqw'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaqw',
            name='bnn',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
